; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_rgblocks:
	.byte 0
	.word @instruments
	.word @samples-4

.export music_data_rgblocks
.global FAMISTUDIO_DPCM_PTR

@instruments:
@samples:


