name: Build ROM

on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#		Might need this later but i probably won't compress the CHR data
#      - name: Setup Python
#        uses: actions/setup-python@v4.6.1
#        with:
#          python-version: '3.10'
#          architecture: 'x64'
#      - name: Install numpy
#        uses: BSFishy/pip-action@v1
#        with:
#          packages: numpy
      - name: Build the game
        run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Game Download
          path: rom
